export const BRAND = {
  name: 'AQALYM ERP',
  nameAr: 'أقاليم',
  tagline: 'نظام الإدارة الصناعية',
  primary: '#1E275E',
  secondary: '#6E7078',
  accent: '#C58D5E',
  background: '#F4F5F8',
  card: '#FFFFFF',
  sidebar: '#151A2E',
  radius: 12,
  chart: {
    primary: '#1E275E',
    accent: '#C58D5E',
    muted: '#A8B0C4',
    success: '#059669',
    warning: '#D97706',
    danger: '#DC2626',
    info: '#3B82F6',
  },
} as const;

export const IRAQI_GOVERNORATES = [
  'بغداد',
  'البصرة',
  'نينوى',
  'أربيل',
  'السليمانية',
  'دهوك',
  'كركوك',
  'الأنبار',
  'ديالى',
  'واسط',
  'ميسان',
  'ذي قار',
  'المثنى',
  'القادسية',
  'بابل',
  'كربلاء',
  'النجف',
  'صلاح الدين',
] as const;
