import type {
  Accessory,
  AppNotification,
  Category,
  CompanySettings,
  Customer,
  GlassType,
  InventoryItem,
  Order,
  OtpLog,
  Product,
  Project,
  Role,
  ServiceItem,
  SpecCatalog,
  StaffUser,
  Variant,
} from '@/domain/entities';
import { DEFAULT_ROLE_PERMISSIONS } from '@/shared/constants/permissions';
import { mergeProductSpecifications } from '@/shared/lib/product-specs';

const now = new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const SEED_ROLES: Role[] = [
  { id: 'role-super', slug: 'super_admin', name: 'Super Admin', nameAr: 'مشرف أعلى', permissions: DEFAULT_ROLE_PERMISSIONS.super_admin, isSystem: true },
  { id: 'role-admin', slug: 'admin', name: 'Admin', nameAr: 'مدير', permissions: DEFAULT_ROLE_PERMISSIONS.admin, isSystem: true },
  { id: 'role-sales', slug: 'sales', name: 'Sales', nameAr: 'مبيعات', permissions: DEFAULT_ROLE_PERMISSIONS.sales, isSystem: true },
  { id: 'role-factory', slug: 'factory', name: 'Factory', nameAr: 'المصنع', permissions: DEFAULT_ROLE_PERMISSIONS.factory, isSystem: true },
  { id: 'role-warehouse', slug: 'warehouse', name: 'Warehouse', nameAr: 'المستودع', permissions: DEFAULT_ROLE_PERMISSIONS.warehouse, isSystem: true },
  { id: 'role-support', slug: 'support', name: 'Support', nameAr: 'دعم العملاء', permissions: DEFAULT_ROLE_PERMISSIONS.support, isSystem: true },
];

export const SEED_STAFF: StaffUser[] = [
  {
    id: 'staff-1',
    email: 'admin@aqalym.iq',
    name: 'أحمد الكاظم',
    phone: '07701234567',
    roleId: 'role-super',
    roleSlug: 'super_admin',
    status: 'active',
    createdAt: daysAgo(90),
    updatedAt: now,
  },
  {
    id: 'staff-2',
    email: 'sales@aqalym.iq',
    name: 'سارة الموسوي',
    phone: '07707654321',
    roleId: 'role-sales',
    roleSlug: 'sales',
    status: 'active',
    createdAt: daysAgo(60),
    updatedAt: now,
  },
  {
    id: 'staff-3',
    email: 'factory@aqalym.iq',
    name: 'حيدر النجفي',
    roleId: 'role-factory',
    roleSlug: 'factory',
    status: 'active',
    createdAt: daysAgo(40),
    updatedAt: now,
  },
];

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-doors', slug: 'doors', name: 'Doors', nameAr: 'أبواب', description: 'Thermal / Sliding', descriptionAr: 'حراري / سحاب', icon: 'door', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', order: 1 },
  { id: 'cat-windows', slug: 'windows', name: 'Windows', nameAr: 'نوافذ', description: 'Casement / Sliding', descriptionAr: 'مفصلية / سحاب', icon: 'window', image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', order: 2 },
  { id: 'cat-facades', slug: 'facades', name: 'Facades', nameAr: 'واجهات', description: 'Curtain wall', descriptionAr: 'واجهة ستارية', icon: 'facade', image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80', order: 3 },
  { id: 'cat-fixed-glass', slug: 'fixed_glass', name: 'Fixed Glass', nameAr: 'زجاج ثابت', description: 'Partitions', descriptionAr: 'قواطع مكتبية', icon: 'glass', image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80', order: 4 },
  { id: 'cat-shutters', slug: 'shutters', name: 'Shutters', nameAr: 'شترات', description: 'Manual / Electric', descriptionAr: 'يدوي / كهربائي', icon: 'shutter', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80', order: 5 },
];

export const SEED_CATALOGS: SpecCatalog[] = [
  {
    id: 'catalog-doors-thermal',
    name: 'Thermal Entrance Doors',
    nameAr: 'أبواب حرارية',
    description: 'Standard specs for thermal-break entrance doors',
    descriptionAr: 'مواصفات قياسية لأبواب المدخل بكسر حراري',
    specifications: [
      { label: 'نظام الألمنيوم', value: 'كسر حراري ٧٠ مم' },
      { label: 'العزل', value: 'عزل حراري عالي' },
      { label: 'الأمان', value: 'قفل متعدد النقاط' },
    ],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'catalog-doors-sliding',
    name: 'Sliding Doors',
    nameAr: 'أبواب سحاب',
    description: 'Standard specs for lift-and-slide doors',
    descriptionAr: 'مواصفات قياسية لأبواب السحاب والرفع',
    specifications: [
      { label: 'نظام الألمنيوم', value: 'رفع وسحب' },
      { label: 'المسار', value: 'ثنائي / ثلاثي' },
    ],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'catalog-windows-casement',
    name: 'Casement Windows',
    nameAr: 'نوافذ مفصلية',
    description: 'Standard specs for casement windows',
    descriptionAr: 'مواصفات قياسية للنوافذ المفصلية',
    specifications: [
      { label: 'نظام الألمنيوم', value: 'كسر حراري ٦٠ مم' },
      { label: 'الفتح', value: 'مفصلي داخلي / خارجي' },
    ],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'catalog-windows-sliding',
    name: 'Sliding Windows',
    nameAr: 'نوافذ سحاب',
    description: 'Standard specs for sliding windows',
    descriptionAr: 'مواصفات قياسية لنوافذ السحاب',
    specifications: [
      { label: 'نظام الألمنيوم', value: 'سحاب ٤٥ مم' },
      { label: 'المسار', value: 'ثنائي' },
    ],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'catalog-facades',
    name: 'Curtain Wall Facades',
    nameAr: 'واجهات ستارية',
    description: 'Standard specs for curtain wall systems',
    descriptionAr: 'مواصفات قياسية لأنظمة الواجهات الستارية',
    specifications: [
      { label: 'النظام', value: 'وحدات جاهزة / تركيب ميداني' },
      { label: 'مقاومة الرياح', value: 'عالية' },
    ],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'catalog-fixed-glass',
    name: 'Fixed Glass Partitions',
    nameAr: 'زجاج ثابت',
    description: 'Standard specs for fixed glass partitions',
    descriptionAr: 'مواصفات قياسية للتقسيمات الزجاجية الثابتة',
    specifications: [
      { label: 'السماكة', value: '١٠–١٢ مم' },
      { label: 'التثبيت', value: 'قناة تثبيت / نقاط عنكبوتية' },
    ],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'catalog-shutters',
    name: 'Roller Shutters',
    nameAr: 'شترات لفّافة',
    description: 'Standard specs for roller shutters',
    descriptionAr: 'مواصفات قياسية للشترات اللفّافة',
    specifications: [
      { label: 'المادة', value: 'ألمنيوم مقوّى' },
      { label: 'التشغيل', value: 'يدوي / كهربائي' },
    ],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'catalog-ready-hardware',
    name: 'Ready Hardware',
    nameAr: 'إكسسوارات جاهزة',
    description: 'Standard specs for ready-made hardware SKUs',
    descriptionAr: 'مواصفات قياسية للمنتجات الجاهزة من الإكسسوارات',
    specifications: [
      { label: 'النوع', value: 'طقم كامل (يد + وردة)' },
      { label: 'المادة', value: 'ألمنيوم مطلي' },
      { label: 'التوافق', value: 'أبواب ألمنيوم قياسية' },
    ],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
];

const colors = [
  { id: 'ral9016', name: 'White', nameAr: 'أبيض', hex: '#F6F6F6' },
  { id: 'ral7016', name: 'Anthracite', nameAr: 'رمادي أنثراسايت', hex: '#383E42' },
  { id: 'ral9005', name: 'Black', nameAr: 'أسود', hex: '#0A0A0A' },
];

function productWithCatalog(
  catalogId: string,
  extraSpecifications: Product['extraSpecifications'],
  base: Omit<Product, 'catalogId' | 'extraSpecifications' | 'specifications'>
): Product {
  const catalog = SEED_CATALOGS.find((c) => c.id === catalogId);
  return {
    ...base,
    catalogId,
    extraSpecifications,
    specifications: mergeProductSpecifications(catalog, extraSpecifications),
  };
}

export const SEED_PRODUCTS: Product[] = [
  productWithCatalog('catalog-doors-thermal', [], {
    id: 'prod-door-pivot',
    categoryId: 'cat-doors',
    categorySlug: 'doors',
    kind: 'custom',
    name: 'Pivot Entrance Door',
    nameAr: 'باب مدخل محوري',
    description: 'Premium thermal break pivot door',
    descriptionAr: 'باب مدخل ألمنيوم محوري فاخر بكسر حراري',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1000&q=80'],
    minimumWidth: 90,
    maximumWidth: 160,
    minimumHeight: 200,
    maximumHeight: 280,
    estimatedPrice: 1850000,
    variants: ['محوري يمين', 'محوري يسار'],
    glassTypes: ['glass-clear', 'glass-double'],
    accessories: ['acc-handle-premium', 'acc-lock-multipoint'],
    colors,
    featured: true,
    createdAt: daysAgo(30),
    updatedAt: now,
  }),
  productWithCatalog('catalog-windows-casement', [], {
    id: 'prod-win-casement',
    categoryId: 'cat-windows',
    categorySlug: 'windows',
    kind: 'custom',
    name: 'Casement Window',
    nameAr: 'نافذة مفصلية',
    description: 'Classic casement aluminum window',
    descriptionAr: 'نافذة ألمنيوم مفصلية كلاسيكية',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=1000&q=80'],
    minimumWidth: 40,
    maximumWidth: 140,
    minimumHeight: 40,
    maximumHeight: 180,
    estimatedPrice: 420000,
    variants: ['ضلفة واحدة', 'ضفلتين'],
    glassTypes: ['glass-clear', 'glass-double', 'glass-reflective'],
    accessories: ['acc-mosquito'],
    colors,
    featured: true,
    createdAt: daysAgo(25),
    updatedAt: now,
  }),
  productWithCatalog('catalog-facades', [], {
    id: 'prod-facade-cw',
    categoryId: 'cat-facades',
    categorySlug: 'facades',
    kind: 'custom',
    name: 'Curtain Wall System',
    nameAr: 'نظام واجهة ستارية',
    description: 'Structural curtain wall',
    descriptionAr: 'واجهة ستارية إنشائية للمشاريع التجارية',
    images: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1000&q=80'],
    minimumWidth: 100,
    maximumWidth: 600,
    minimumHeight: 100,
    maximumHeight: 500,
    estimatedPrice: 950000,
    variants: ['تركيب ميداني', 'وحدات جاهزة'],
    glassTypes: ['glass-double', 'glass-reflective'],
    accessories: [],
    colors: colors.slice(0, 2),
    featured: true,
    createdAt: daysAgo(20),
    updatedAt: now,
  }),
  productWithCatalog('catalog-shutters', [{ label: 'ملاحظة', value: 'محرك كهربائي مدمج' }], {
    id: 'prod-shutter-electric',
    categoryId: 'cat-shutters',
    categorySlug: 'shutters',
    kind: 'ready',
    name: 'Electric Shutter',
    nameAr: 'شتر كهربائي',
    description: 'Motorized roller shutter',
    descriptionAr: 'شتر رول كهربائي',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&q=80'],
    minimumWidth: 80,
    maximumWidth: 400,
    minimumHeight: 100,
    maximumHeight: 350,
    estimatedPrice: 750000,
    variants: ['يدوي', 'كهربائي'],
    glassTypes: [],
    accessories: ['acc-motor'],
    colors,
    featured: false,
    createdAt: daysAgo(15),
    updatedAt: now,
  }),
];

export const SEED_VARIANTS: Variant[] = [
  {
    id: 'var-1',
    productId: 'prod-door-pivot',
    name: 'Right Pivot',
    nameAr: 'محوري يمين',
    price: 1850000,
    images: [],
    specifications: [{ label: 'الاتجاه', value: 'يمين' }],
    createdAt: daysAgo(10),
    updatedAt: now,
  },
  {
    id: 'var-2',
    productId: 'prod-door-pivot',
    name: 'Left Pivot',
    nameAr: 'محوري يسار',
    price: 1850000,
    images: [],
    specifications: [{ label: 'الاتجاه', value: 'يسار' }],
    createdAt: daysAgo(10),
    updatedAt: now,
  },
  {
    id: 'var-3',
    productId: 'prod-win-casement',
    name: 'Single Leaf',
    nameAr: 'ضلفة واحدة',
    price: 420000,
    images: [],
    specifications: [],
    createdAt: daysAgo(8),
    updatedAt: now,
  },
];

export const SEED_GLASS: GlassType[] = [
  { id: 'glass-clear', name: 'Clear Tempered', nameAr: 'مقسّى شفاف', description: 'Standard tempered', descriptionAr: 'زجاج مقسّى شفاف قياسي', thickness: 8, color: 'شفاف', pricePerSqm: 45000, image: '' },
  { id: 'glass-double', name: 'Double Glazing', nameAr: 'زجاج مزدوج', description: 'Insulated unit', descriptionAr: 'وحدة زجاج مزدوج عازلة', thickness: 24, color: 'شفاف', pricePerSqm: 85000 },
  { id: 'glass-reflective', name: 'Reflective', nameAr: 'عاكس', description: 'Solar control', descriptionAr: 'زجاج عاكس للتحكم بالطاقة', thickness: 8, color: 'رمادي', pricePerSqm: 95000 },
  { id: 'glass-laminated', name: 'Laminated', nameAr: 'مصفح أمان', description: 'Safety laminated', descriptionAr: 'زجاج مصفح للأمان', thickness: 10, color: 'شفاف', pricePerSqm: 110000 },
];

export const SEED_ACCESSORIES: Accessory[] = [
  { id: 'acc-handle-premium', category: 'مقابض', name: 'Premium Handle', nameAr: 'مقبض فاخر', description: 'European handle set', descriptionAr: 'طقم مقابض أوروبي فاخر', price: 75000 },
  { id: 'acc-lock-multipoint', category: 'أقفال', name: 'Multipoint Lock', nameAr: 'قفل متعدد النقاط', description: 'Security lock', descriptionAr: 'قفل أمان متعدد النقاط', price: 120000 },
  { id: 'acc-mosquito', category: 'شبك', name: 'Mosquito Net', nameAr: 'شبك ناموسيات', description: 'Integrated mesh', descriptionAr: 'شبك ناموسيات مدمج', price: 55000 },
  { id: 'acc-motor', category: 'محركات', name: 'Motor System', nameAr: 'نظام كهربائي', description: 'Electric drive', descriptionAr: 'نظام تشغيل كهربائي', price: 250000 },
];

export const SEED_SERVICES: ServiceItem[] = [
  {
    id: 'svc-1',
    title: 'Site Survey',
    titleAr: 'مسح ميداني',
    description: 'Professional measurement visit',
    descriptionAr: 'زيارة قياس احترافية للموقع',
    images: ['https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80'],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'svc-2',
    title: 'Installation',
    titleAr: 'التركيب',
    description: 'Certified installation team',
    descriptionAr: 'فريق تركيب معتمد',
    images: ['https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80'],
    createdAt: daysAgo(40),
    updatedAt: now,
  },
  {
    id: 'svc-3',
    title: 'Maintenance',
    titleAr: 'الصيانة',
    description: 'After-sales maintenance',
    descriptionAr: 'صيانة ما بعد البيع',
    images: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80'],
    createdAt: daysAgo(35),
    updatedAt: now,
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'محمد العبيدي',
    phone: '07701112233',
    email: 'mohammed@example.com',
    governorate: 'بغداد',
    city: 'الكرادة',
    addresses: [{ id: 'addr-1', label: 'المنزل', governorate: 'بغداد', city: 'الكرادة', address: 'شارع ١٤ رمضان', isDefault: true }],
    createdAt: daysAgo(50),
    updatedAt: now,
  },
  {
    id: 'cust-2',
    name: 'نور الساعدي',
    phone: '07804445566',
    governorate: 'البصرة',
    city: 'العشار',
    addresses: [{ id: 'addr-2', label: 'العمل', governorate: 'البصرة', city: 'العشار', address: 'قرب كورنيش شط العرب', isDefault: true }],
    createdAt: daysAgo(20),
    updatedAt: now,
  },
  {
    id: 'cust-3',
    name: 'شركة النور للمقاولات',
    phone: '07709998877',
    email: 'info@alnoor.iq',
    governorate: 'أربيل',
    city: 'أربيل',
    addresses: [{ id: 'addr-3', label: 'الموقع', governorate: 'أربيل', city: 'أربيل', address: 'شارع ١٠٠ متر', isDefault: true }],
    notes: 'عميل مشاريع كبيرة',
    createdAt: daysAgo(80),
    updatedAt: now,
  },
];

function makeTimeline(status: Order['status'], createdAt: string): Order['timeline'] {
  const steps: Order['status'][] = ['submitted', 'under_review', 'approved', 'sent_to_factory', 'in_production', 'ready', 'installation', 'completed'];
  const labels: Record<string, string> = {
    submitted: 'تم تقديم الطلب',
    under_review: 'قيد المراجعة',
    approved: 'تم الاعتماد',
    rejected: 'مرفوض',
    sent_to_factory: 'أُرسل للمصنع',
    in_production: 'بدء الإنتاج',
    ready: 'جاهز',
    installation: 'بدء التركيب',
    completed: 'مكتمل',
    cancelled: 'ملغى',
  };
  const idx = steps.indexOf(status as typeof steps[number]);
  const end = idx >= 0 ? idx : 0;
  return steps.slice(0, end + 1).map((s, i) => ({
    status: s,
    label: labels[s]!,
    at: new Date(new Date(createdAt).getTime() + i * 86400000).toISOString(),
    by: i === 0 ? 'العميل' : 'فريق عقاليم',
  }));
}

export const SEED_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'AQ-2026-001',
    customerId: 'cust-1',
    customerName: 'محمد العبيدي',
    customerPhone: '07701112233',
    orderKind: 'custom',
    categoryId: 'cat-doors',
    categorySlug: 'doors',
    categoryName: 'أبواب',
    productId: 'prod-door-pivot',
    productName: 'باب مدخل محوري',
    productImage: SEED_PRODUCTS[0]!.images[0],
    measurements: { width: 120, height: 240, quantity: 1 },
    selectedVariant: 'محوري يمين',
    selectedGlass: 'glass-double',
    selectedAccessories: ['acc-handle-premium'],
    selectedColor: 'ral7016',
    location: { governorate: 'بغداد', city: 'الكرادة', address: 'شارع ١٤ رمضان', latitude: 33.3152, longitude: 44.3661 },
    estimatedPrice: 2100000,
    finalPrice: 2100000,
    status: 'under_review',
    notes: 'يرجى التواصل قبل الزيارة',
    images: [],
    timeline: makeTimeline('under_review', daysAgo(2)),
    createdAt: daysAgo(2),
    updatedAt: now,
  },
  {
    id: 'ord-2',
    orderNumber: 'AQ-2026-002',
    customerId: 'cust-2',
    customerName: 'نور الساعدي',
    customerPhone: '07804445566',
    orderKind: 'custom',
    categoryId: 'cat-windows',
    categorySlug: 'windows',
    categoryName: 'نوافذ',
    productId: 'prod-win-casement',
    productName: 'نافذة مفصلية',
    productImage: SEED_PRODUCTS[1]!.images[0],
    measurements: { width: 100, height: 140, quantity: 4 },
    selectedVariant: 'ضفلتين',
    selectedGlass: 'glass-reflective',
    selectedAccessories: ['acc-mosquito'],
    location: { governorate: 'البصرة', city: 'العشار', address: 'قرب كورنيش شط العرب' },
    estimatedPrice: 1850000,
    finalPrice: 1800000,
    status: 'approved',
    timeline: makeTimeline('approved', daysAgo(5)),
    createdAt: daysAgo(5),
    updatedAt: now,
  },
  {
    id: 'ord-3',
    orderNumber: 'AQ-2026-003',
    customerId: 'cust-3',
    customerName: 'شركة النور للمقاولات',
    customerPhone: '07709998877',
    orderKind: 'custom',
    categoryId: 'cat-facades',
    categorySlug: 'facades',
    categoryName: 'واجهات',
    productId: 'prod-facade-cw',
    productName: 'نظام واجهة ستارية',
    productImage: SEED_PRODUCTS[2]!.images[0],
    measurements: { width: 400, height: 300, quantity: 12 },
    selectedVariant: 'وحدات جاهزة',
    selectedGlass: 'glass-reflective',
    selectedAccessories: [],
    location: { governorate: 'أربيل', city: 'أربيل', address: 'شارع ١٠٠ متر' },
    estimatedPrice: 12500000,
    finalPrice: 12000000,
    status: 'in_production',
    timeline: makeTimeline('in_production', daysAgo(12)),
    createdAt: daysAgo(12),
    updatedAt: now,
  },
  {
    id: 'ord-4',
    orderNumber: 'AQ-2026-004',
    customerId: 'cust-1',
    customerName: 'محمد العبيدي',
    customerPhone: '07701112233',
    orderKind: 'ready',
    categoryId: 'cat-shutters',
    categorySlug: 'shutters',
    categoryName: 'شترات',
    productId: 'prod-shutter-electric',
    productName: 'شتر كهربائي',
    productImage: SEED_PRODUCTS[3]!.images[0],
    measurements: { width: 200, height: 250, quantity: 2 },
    selectedVariant: 'كهربائي',
    selectedAccessories: ['acc-motor'],
    location: { governorate: 'بغداد', city: 'الكرادة', address: 'شارع ١٤ رمضان' },
    estimatedPrice: 1500000,
    finalPrice: 1500000,
    status: 'completed',
    timeline: makeTimeline('completed', daysAgo(40)),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
  },
  {
    id: 'ord-5',
    orderNumber: 'AQ-2026-005',
    customerId: 'cust-2',
    customerName: 'نور الساعدي',
    customerPhone: '07804445566',
    orderKind: 'custom',
    categoryId: 'cat-doors',
    categorySlug: 'doors',
    categoryName: 'أبواب',
    productId: 'prod-door-pivot',
    productName: 'باب مدخل محوري',
    measurements: { width: 110, height: 230, quantity: 1 },
    selectedAccessories: [],
    location: { governorate: 'البصرة', city: 'العشار', address: 'حي الجزائر' },
    estimatedPrice: 0,
    status: 'submitted',
    notes: 'طلب جديد — بانتظار التسعير',
    timeline: makeTimeline('submitted', daysAgo(0)),
    createdAt: daysAgo(0),
    updatedAt: now,
  },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'Commercial Tower Facade',
    titleAr: 'واجهة برج تجاري',
    description: 'Full curtain wall system',
    descriptionAr: 'تنفيذ واجهة ستارية كاملة لبرج تجاري',
    governorate: 'بغداد',
    images: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80'],
    videos: [],
    completionDate: daysAgo(60),
    category: 'واجهات',
    createdAt: daysAgo(100),
    updatedAt: daysAgo(60),
  },
  {
    id: 'proj-2',
    title: 'Villa Glazing Package',
    titleAr: 'حزمة زجاج فيلا',
    description: 'Doors and windows package',
    descriptionAr: 'أبواب ونوافذ حرارية لفيلا سكنية',
    governorate: 'أربيل',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80'],
    videos: [],
    completionDate: daysAgo(30),
    category: 'أبواب ونوافذ',
    createdAt: daysAgo(80),
    updatedAt: daysAgo(30),
  },
];

export const SEED_NOTIFICATIONS: AppNotification[] = [
  { id: 'notif-1', title: 'طلب جديد', body: 'تم استلام الطلب AQ-2026-005', channel: 'system', orderId: 'ord-5', read: false, createdAt: daysAgo(0) },
  { id: 'notif-2', title: 'جاهز للتركيب', body: 'الطلب AQ-2026-003 قيد الإنتاج', channel: 'push', orderId: 'ord-3', read: false, createdAt: daysAgo(1) },
  { id: 'notif-3', title: 'اكتمال طلب', body: 'تم إكمال الطلب AQ-2026-004', channel: 'system', orderId: 'ord-4', read: true, createdAt: daysAgo(10) },
];

export const SEED_OTP_LOGS: OtpLog[] = [
  { id: 'otp-1', phone: '07701112233', purpose: 'login', success: true, createdAt: daysAgo(1) },
  { id: 'otp-2', phone: '07804445566', purpose: 'order', success: true, createdAt: daysAgo(2) },
  { id: 'otp-3', phone: '07709998877', purpose: 'login', success: false, createdAt: daysAgo(3) },
];

export const SEED_INVENTORY: InventoryItem[] = [
  { id: 'inv-1', sku: 'ALU-70', name: 'Aluminum Profile 70mm', nameAr: 'بروفيل ألمنيوم ٧٠ مم', quantity: 2450, unit: 'متر', reorderLevel: 100, updatedAt: now },
  { id: 'inv-2', sku: 'GLS-DBL', name: 'Double Glass Unit', nameAr: 'وحدة زجاج مزدوج', quantity: 842, unit: 'م²', reorderLevel: 30, updatedAt: now },
  { id: 'inv-3', sku: 'ACC-HDL', name: 'Premium Handles', nameAr: 'مقابض فاخرة', quantity: 18, unit: 'قطعة', reorderLevel: 20, updatedAt: now },
  { id: 'inv-4', sku: 'ALU-E102', name: 'Aluminum Section E-102', nameAr: 'قطاع ألمنيوم E-102', quantity: 12, unit: 'متر', reorderLevel: 50, updatedAt: now },
  { id: 'inv-5', sku: 'RUB-EPDM', name: 'EPDM Sealing Rubber', nameAr: 'مطاط ختم EPDM', quantity: 315, unit: 'متر', reorderLevel: 80, updatedAt: now },
];

export const SEED_SETTINGS: CompanySettings = {
  companyName: 'AQALYM',
  companyNameAr: 'عقاليم',
  phone: '07700000000',
  email: 'info@aqalym.iq',
  address: 'بغداد — العراق',
  governorate: 'بغداد',
  otpEnabled: true,
  otpLength: 6,
  otpExpiryMinutes: 5,
  storageFolder: 'aqalym',
  fcmEnabled: true,
  currency: 'IQD',
  timezone: 'Asia/Baghdad',
};
